// <auto-generated />
namespace SSPC_One_HCP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class xxx3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xxx3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005080938258_xxx3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
