// <auto-generated />
namespace SSPC_One_HCP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20200228001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200228001));
        
        string IMigrationMetadata.Id
        {
            get { return "202002280627456_20200228001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
